# config.yaml
seeding:
  symbols:
    - GLD
    - SPY
    - AGG
    - TLT
    - VCIT
    - LQD
    - HYG
    - VNQ
    - SLV
    - QQQ
    - XLK
    - XLF
    - XLE
    - XLV
    - XLI
    - XLY
    - XLP
    - XLU
    - XME
    - GDX
    - IWM
  start_date: "2008-01-01"
  end_date: "2026-03-31"
  sources:
    price: "yfinance"
    macro: "fred"
  update_frequency: "daily"

daily_update:
  symbols: []
  update_range: "last_5_trading_days"
  sources:
    price: "yfinance"
    macro: "fred"
  retrain_models: false

categories:
  fi_commodities:
    - TLT
    - VCIT
    - LQD
    - HYG
    - VNQ
    - GLD
    - SLV
  equities:
    - QQQ
    - XLK
    - XLF
    - XLE
    - XLV
    - XLI
    - XLY
    - XLP
    - XLU
    - XME
    - GDX
    - IWM
  benchmarks:
    - SPY
    - AGG
