# config.yaml
seeding:
  symbols:
    - GLD
    - SPY
    - AGG
    - TLT
    - VCIT
    - LQD
    - HYG
    - VNQ
    - SLV
    - QQQ
    - XLK
    - XLF
    - XLE
    - XLV
    - XLI
    - XLY
    - XLP
    - XLU
    - XME
    - GDX
    - IWM
    - IWF
    - XSD
    - XBI
    - XLB
    - XLRE
    - IWD
    - IWO
  macro_config:
    VIX: ["VIXCLS", "^VIX"]
    DXY: ["DTWEXBGS", "DXY"]
    T10Y2Y: ["T10Y2Y", null]
    TBILL_3M: ["DTB3", "^IRX"]
    IG_SPREAD: ["BAMLC0A0CM", null]
    DGS1MO: "DGS1MO"
    DGS3MO: "DGS3MO"
    DGS6MO: "DGS6MO"
    DGS1: "DGS1"
    DGS2: "DGS2"
    DGS5: "DGS5"
    DGS7: "DGS7"
    DGS10: "DGS10"
    DGS20: "DGS20"
    DGS30: "DGS30"
    HY_SPREAD: ["BAMLH0A0HYM2", null]
  start_date: "2008-01-01"
  end_date: "2030-12-31"
  sources:
    price: "yfinance"
    macro: "fred"
  update_frequency: "daily"

daily_update:
  symbols: []
  update_range: "last_5_trading_days"
  sources:
    price: "yfinance"
    macro: "fred"
  retrain_models: false

categories:
  fi_commodities:
    - TLT
    - VCIT
    - LQD
    - HYG
    - VNQ
    - GLD
    - SLV
  equities:
    - QQQ
    - XLK
    - XLF
    - XLE
    - XLV
    - XLI
    - XLY
    - XLP
    - XLU
    - XME
    - GDX
    - IWM
    - IWD
    - IWO
  benchmarks:
    - SPY
    - AGG
